//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Truco.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Truco.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BairroId;CidadeId;Nome;NomeAbreviado;NomeFonetizado
        ///21A5721E-AF5F-471B-89E7-00039D794ED3;5C85398E-7B8D-4BD8-A384-920E0EAC1E8C;Centro;NULL;SMTO
        ///5617C163-6E03-4629-9CBE-0003C0E7FFD8;519EEC99-D396-484A-8EFF-4E98A9F64E37;Centro;NULL;SMTO
        ///856E32B7-5E28-4F50-9607-00056B7940C0;75F07BED-55C7-4E99-AEE5-35ADBE1A330D;Posse;NULL;POSE
        ///BC60CB76-4EF3-4D00-BEAB-0005D7ECAE2F;4302AB83-68E1-4D69-BB95-9D811991E099;Jardim Arizona;NULL;JARDIM ARISOMA
        ///B46859C6-86A3-4A0D-AFFE-0006DAA1BCD8;71399882-8B6D-4178-A35D-7ED9ED8923DA; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Bairros {
            get {
                return ResourceManager.GetString("Bairros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CidadeId;EstadoId;Nome;Cep
        ///CA000A72-4116-4454-AE38-00043EE48A58;B00AB2FB-54C2-44A9-BE3A-EB47CF4C9ADD;Arraias;77330000
        ///367AF575-809E-4696-994B-000E7277FC19;97D264BC-BBD8-451E-9606-883C702C265B;Tumiritinga;35125000
        ///F22266AA-C8C9-4137-A9E0-001788D9CAB6;ED21D60B-AE1B-4A3D-A5CE-832B32BB94A8;Guaporema;87810000
        ///502FC240-3C70-4398-B211-001AB04370D4;DCC4C786-6E14-4AC3-9999-87EB70AB3461;Campo Erê;89980000
        ///C2254222-C235-4094-9543-0022B99D3539;0F9648DA-E225-4420-B13A-64C11C078CF7;Campina das Missões;98975000
        ///4E1B [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Cidades {
            get {
                return ResourceManager.GetString("Cidades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EstadoId;PaisId;Nome;Sigla;DataUltimaModificacao;DataCriacao;UsuarioCriacao;UsuarioUltimaModificacao
        ///6D0B4FB1-1FBB-44B4-BBDA-0B837ADAD8C0;C277EE77-2F9A-463D-8057-ADFE58650317;Maranhão;MA;2015-07-10 19:35:14.660;2015-07-10 19:35:14.660;NULL;NULL
        ///E09925E3-E0DF-464E-8A36-0F96CFACDBCE;C277EE77-2F9A-463D-8057-ADFE58650317;Rio Grande do Norte;RN;2015-07-10 19:35:14.660;2015-07-10 19:35:14.660;NULL;NULL
        ///A5BB31BD-994B-4CB0-906D-0FE9FB7DED5A;C277EE77-2F9A-463D-8057-ADFE58650317;Piauí;PI;2015-07-10 19:35:14.660;20 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Estados {
            get {
                return ResourceManager.GetString("Estados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogradouroId;BairroId;Descricao;DescricaoFonetizado;Cep
        ///57F20081-CD0B-4EA3-8E43-000006F58360;B62CF536-A4B4-4ED0-B2A6-B9B6BA99DDCA;Rua Luiz Germoglio;RUA RUIS JSMOGIO;58051742
        ///ED298392-E870-41B3-BF92-00000A74290E;0A74F5CA-08C4-4009-9E53-EBC0EFF66272;Rua Emílio Bueler;RUA EMIRIO BUERE;89026327
        ///9DFFB200-2C27-47A7-AB54-00005E4B7BB1;835A3E8E-AFB3-430F-8991-EC0EB42CE432;Rua RB 28 A;RUA RB 28 A;74474341
        ///B2BF0670-ACE8-4865-8BE2-0000662EE52D;C8E216DC-339A-47E1-BCA0-45963276B3E6;Quadra 27 Conjunto B;KUADRA 27 KJU [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Logradouros {
            get {
                return ResourceManager.GetString("Logradouros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PaisId;Nome;Sigla;DataUltimaModificacao;DataCriacao;UsuarioCriacao;UsuarioUltimaModificacao
        ///C277EE77-2F9A-463D-8057-ADFE58650317;Brasil;BRA;2015-07-10 19:35:14.470;2015-07-10 19:35:14.470;NULL;NULL
        ///.
        /// </summary>
        public static string Pais {
            get {
                return ResourceManager.GetString("Pais", resourceCulture);
            }
        }
    }
}
