// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using Truco.Backend.Data;

namespace Truco.Backend.Data.Migrations
{
    [DbContext(typeof(TrucoDbContext))]
    [Migration("20180225183020_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Truco.Backend.Models.Pais", b =>
                {
                    b.Property<Guid>("PaisId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasMaxLength(3);

                    b.HasKey("PaisId");

                    b.ToTable("Paises");
                });
#pragma warning restore 612, 618
        }
    }
}
